// Static data for the ideas
const ideasData = [
    {
        id: 1,
        title: "Using AI to Grade APA Style",
        author: "Glori Hinck",
        email: "ghinck@stthomas.edu",
        department: "STELAR",
        date: "2025-04-17",
        description: "This implementation will describe the prompt strategies used to evaluate adherence to APA style in a student-submitted paper and will share a prompt that others can adapt for use in their own courses. One recommended teaching strategy is to have students analyze their own papers with this prompt and to make recommended changes before submitting for grading. The faculty member can then run the same prompt for final grading. Always be sure to use a system and security settings to optimize data security (i.e., redact student names, do not allow data to be used to train the AI model).",
        aiTools: ["other"],
        useCases: ["assessment", "student-feedback", "research"],
        resourceType: "pdf",
        resourceUrl: "/ai-idea-book/public/resources/apa-style-grading-with-ai.pdf",
        tags: ["citation style", "APA", "grading", "feedback"]
    },
    {
        id: 2,
        title: "Water Quality Coach ",
        author: "Jonathan Keiser",
        email: "keis2759@stthomas.edu",
        department: "ITS/STELAR",
        date: "2025-05-07",
        description: "The Water Quality Coach was created to help Geology students understand basic water quality concepts and interpret their water quality samples. Download the attached slides to learn how four different generative AI platforms (ChatGPT, Hugging Face, Claude Project, NotebookLM) were used to create personalized learning tools to help student interpret and understand water quality data. The slides describe the pros and cons of each tool based on its functionality and links are provided for each custom GPT. You will need to log in or create an account for each tool in order to view.",
        aiTools: ["chatgpt", "huggingface", "claude", "notebooklm"],
        useCases: ["collaboration", "assessment", "student-feedback"],
        resourceType: "pdf",
        resourceUrl: "/ai-idea-book/public/resources/water-quality-coach.pdf",
        tags: ["geology", "personalized learning"]
    },
    {
        id: 3,
        title: "Creating Personalized Progress Reports with ChatGPT",
        author: "Candace Chou",
        email: "ccchou@stthomas.edu",
        department: "Education",
        date: "2025-05-07",
        description: "Describes how to use ChatGPT to generate individualized mid-term progress reports for students. These reports include grading criteria, points earned from all assignments, letter grade, and a personalized message. Includes a reflection on the process.",
        aiTools: ["chatgpt"],
        useCases: ["content-creation", "assessment"],
        resourceType: "pdf",
        resourceUrl: "/ai-idea-book/public/resources/creating-personalized-progress-reports-with-chatgpt.pdf",
        tags: ["grading", "communication"]
    },
    {
        id: 4,
        title: "Periodic Table Classification Game",
        author: "Jonathan Keiser",
        email: "keis2759@stthomas.edu",
        department: "ITS/STELAR",
        date: "2025-05-09",
        description: "The Periodic Table Game was created with the following prompt in Claude Artifact: 'You are an expert in chemistry education and the periodic table. Create an HTML game using Java Script and CSS to help student memorize and understand the periodic table of elements focusing on names and symbols of elements. Approach this in a step-by-step manner. Do you have any clarifying questions?'<br><br>NOTE: Claude Artifact is required to create this game.",
        aiTools: ["Claude Artifacts"],
        useCases: ["content-creation", "assessment"],
        resourceType: "url",
        resourceUrl: "https://claude.site/artifacts/ee8e2d73-be0d-44fe-8cd9-4befc302c9a5",
        tags: ["gamification", "chemistry", "periodic table"]
    },
    {
        id: 5,
        title: "Microbiology Concept Mapping Activity",
        author: "Joanna Klein",
        email: "joanna.klein@stthomas.edu",
        department: "Biology",
        date: "2025-05-09",
        description: "This video demonstrates how to use AI to design a concept mapping activity for a microbiology lecture for nursing students. The goal is for students to apply the principles of bacterial pathogenesis to the bacterium Streptococcus Pyogenes.",
        aiTools: ["Claude"],
        useCases: ["content-creation", "research"],
        resourceType: "url",
        resourceUrl: "https://stthomas.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=53b3c3e4-2865-4acc-b02b-b2d501355522&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&captions=false&interactivity=all",
        tags: ["concept map", "microbiology", "science", "nursing", "bacterial pathogenesis"]
    },
    {
        id: 6,
        title: "Modification of a Script for a Role Playing Activity",
        author: "Joanna Klein",
        email: "joanna.klein@stthomas.edu",
        department: "Biology",
        date: "2025-05-09",
        description: "This video demonstrates how AI was used to update the dialogue in a role-playing activity related to convincing someone to get a flu shot.",
        aiTools: ["claude"],
        useCases: ["content-creation"],
        resourceType: "url",
        resourceUrl: "https://stthomas.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=93a8a15d-cbdf-413d-a3c3-b2d501354f11&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&captions=false&interactivity=all",
        tags: ["nursing", "efficiency", "role play"]
    },
    {
        id: 7,
        title: "Creation of a Microbiology Tutor Bot",
        author: "Joanna Klein",
        email: "joanna.klein@stthomas.edu",
        department: "Biology",
        date: "2025-05-09",
        description: "This video demonstrates how to design and train an AI tutor to help student understand pathogens presented in a medical case study.<br><br>Visit this link to use the tutor: <a href='https://box.boodle.ai/a/@MicroMentor' target='_blank'>https://box.boodle.ai/a/@MicroMentor</a><br><br>NOTE: If you do not have a BoodleBox account, you will be prompted to create a free account when you click on the link. A free account will allow a limited number of interactions with the bot.",
        aiTools: ["claude"],
        useCases: ["content-creation"],
        resourceType: "url",
        resourceUrl: "https://stthomas.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=b45d5efd-66d9-43d2-86a5-b2d50135469d&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&captions=false&interactivity=all",
        tags: ["tutor bot", "microbiology", "nursing", "biology", "science"]
    },
    {
        id: 8,
        title: "Assignment Design and Rubric Creation for a Three Minute Thesis in Microbiology",
        author: "Joanna Klein",
        email: "joanna.klein@stthomas.edu",
        department: "Biology",
        date: "2025-05-09",
        description: "This video demonstrates how to build an assignment and associated grading rubric for a science communication project in which students give a three-minute thesis.",
        aiTools: ["claude"],
        useCases: ["content-creation"],
        resourceType: "url",
        resourceUrl: "https://stthomas.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=262c82de-6eff-4a72-9ab6-b2d501354be2&autoplay=false&offerviewer=true&showtitle=true&showbrand=false&captions=false&interactivity=all",
        tags: ["assignment design", "grading rubric", "student presentation", "microbiology", "biology"]
    }
];
